config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end

  def new
    @appointment = Appointment.new
    @all_doctors = Doctor.all
    @all_patients = Patient.all
  end

  def create
    @appointment = Appointment.new(appointment_params)
    # redirect_to doctor_path(@appointments.doctor)
    if @appointment.save
      redirect_to doctor_path(@appointment.doctor)
    else
      render :new
    end
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date, :notes, :doctor_id, :patient_id) 
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def show
    @doctor = Doctor.find(params[:id])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def show
    @patient = Patient.find(params[:id])
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/index.html.erb
<h1> index </h1>

app/views/appointments/new.html.erb
<h1> New Appointment Form </h1>
<%= form_for @appointment do |f| %>
  <%= f.label "Patient Name:" %>
  <%= f.collection_select :patient_id, @all_patients, :id, :name %>
  <br>
    <%= f.label "Doctor Name:" %>
    <%= f.collection_select :doctor_id, @all_doctors, :id, :name %>
  <br>
    <%= f.label "Date" %>
  <%= f.text_field :date %>
  <br>
  <%= f.label "Notes" %>
  <%= f.text_area :notes %>
  <br>
  <%= f.submit %>
<% end %>

app/views/doctors/show.html.erb
<h1>Doctor page</h1>
<%= @doctor.name %>
<br>
<h2> Patients List </h2>
  <% @doctor.patients.uniq.each do |patient| %>
  <%= link_to patient.name, patient_path(patient) %>
<br>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsOffice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/show.html.erb
<h1>Patient page</h1>
<%= @patient.name %>
<br>
<h2> Doctors </h2>
  <% @patient.doctors.uniq.each do |doctor| %>
  <%= link_to doctor.name, doctor_path(doctor) %>
<br>
  <% doctor.appointments.each do |apt| %>
    <%= apt.date %>
  <h3> Appointment Notes: </h3>
    <%= apt.notes %>
<% end %>
<% end %>